const clothing = [
    {
        id:      0,
        price:   200,
        title:   'Футболка "Эволюционируй или Сдохни"',
        size:    'S/M/L',
        color:   ['blue', 'beige', 'gray'],
        isNew:   false,
        img:     './src/assets/kolesatshirt.png',
        details: 'Брендированная футболка Материал: Хлопок 80%, Вискоза 20%',
        advice:  'Написать дяде Рику для уточнения.',
    },
    {
        id:      1,
        price:   250,
        title:   'Футболка <Frontend>',
        size:    'S/M',
        color:   ['blue', 'beige', 'gray'],
        isNew:   true,
        img:     './/src/assets/frontendtshirt.jpg',
        details: 'Футболка Материал: Хлопок 80%, Вискоза 20%',

    },
    {
        id:      2,
        price:   300,
        title:   'Свитшот',
        size:    'S/L',
        color:   ['blue', 'beige', 'gray'],
        isNew:   true,
        img:     './src/assets/kolesasweatshirt.jpg',
        details: 'Брендированный Свитшот Материал: Хлопок 80%, Вискоза 20%',
    },
    {
        id:      3,
        price:   350,
        title:   'Свитшот Front end developer by day',
        size:    'M/L',
        color:   ['blue', 'beige', 'gray'],
        isNew:   false,
        img:     './src/assets/frontendsweatshirt.jpg',
        details: 'Свитшот Материал: Хлопок 80%, Вискоза 20%',
        advice:  'Написать дяде Морти для уточнения.',
    },
    {
        id:      4,
        price:   400,
        title:   'Худи React',
        size:    'S/M/L',
        color:   ['blue', 'beige', 'gray'],
        isNew:   false,
        img:     './src/assets/react1.jpg',
        details: 'Брендированный Худи Материал: Хлопок 80%, Вискоза 20%',
    },
    {
        id:      5,
        price:   225,
        title:   'Худи Frontend Happy Hour',
        size:    'S',
        color:   ['blue', 'beige', 'gray'],
        isNew:   false,
        img:     './src/assets/hoodie.jpg',
        details: 'Худи Материал: Хлопок 80%, Вискоза 20%',
    },
];
const accessories = [
    {
        id:      6,
        price:   100,
        title:   'Бутылка',
        volume:  0.7,
        isNew:   false,
        img:     './src/assets/kolesabottle.jpg',
        details: 'Бутылка для воды с трубочкой',
    },
    {
        id:               7,
        price:            125,
        title:            'Зонт',
        accessoriesColor: 'Синий/Красный/Черный',
        isNew:            false,
        img:              './src/assets/umbrella.jpg',
    },
    {
        id:               8,
        price:            50,
        title:            'Картхолдер',
        accessoriesColor: 'Синий/Красный/Черный',
        isNew:            false,
        img:              './src/assets/cartholder.jpg',
    },
    {
        id:      9,
        price:   120,
        title:   'Бутылка',
        isNew:   true,
        volume:  1,
        img:     './src/assets/kolesabottle.jpg',
        details: 'Бутылка для воды с трубочкой',
    },
    {
        id:               10,
        price:            175,
        title:            'Зонт',
        accessoriesColor: 'Синий/Красный/Черный',
        isNew:            false,
        img:              './src/assets/umbrella.jpg',
    },
    {
        id:               11,
        price:            75,
        title:            'Картхолдер',
        accessoriesColor: 'Синий/Красный/Черный',
        isNew:            true,
        img:              './src/assets/cartholder.jpg',
    },
];

const allProducts = clothing.concat(accessories);

export { clothing, accessories, allProducts };
